### ISSUE TITLE
Adding two filters: 

### ISSUE THREAD

**Issue by jiayueLiiu** [brian-team/brian2hears#8]
Hi, I'm trying to add the two filters together, one is a time varying filter, with the ControlFilterbank, and another is a time constant filter. But they work fine individually, but whenever I want to add them up, there would be a befferable error:

Testing click response
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /var/folders/90/kzfs8w0n41l1699xdzpf02300000gn/T/brian_debug_gsev8_xg.log  Additionally, you can also include a copy of the script that was run, available at: /var/folders/90/kzfs8w0n41l1699xdzpf02300000gn/T/brian_script_7_789byb.py Thanks! [brian2]
Traceback (most recent call last):
  File "zilany_test.py", line 46, in <module>
    net.run(duration * 1.5)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2/core/base.py", line 280, in device_override_decorated_function
    return func(*args, **kwds)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2/units/fundamentalunits.py", line 2392, in new_f
    result = f(*args, **kwds)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2/core/network.py", line 1094, in run
    obj.run()
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2/core/operations.py", line 87, in run
    self.function(self._clock.t)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbankgroup.py", line 31, in __call__
    self.buffer = self.filterbank.buffer_fetch(self.buffer_start, self.buffer_end)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 787, in buffer_fetch
    return self.output.buffer_fetch(start, end)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 787, in buffer_fetch
    return self.output.buffer_fetch(start, end)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 95, in buffer_fetch
    newsegment = self._buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 117, in _buffer_fetch_next
    return self.buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 236, in buffer_fetch_next
    input = self.source.buffer_fetch(start, end)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 95, in buffer_fetch
    newsegment = self._buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 117, in _buffer_fetch_next
    return self.buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 536, in buffer_fetch_next
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 536, in <genexpr>
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 95, in buffer_fetch
    newsegment = self._buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 117, in _buffer_fetch_next
    return self.buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 536, in buffer_fetch_next
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 536, in <genexpr>
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 95, in buffer_fetch
    newsegment = self._buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 117, in _buffer_fetch_next
    return self.buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 536, in buffer_fetch_next
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 536, in <genexpr>
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 95, in buffer_fetch
    newsegment = self._buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 117, in _buffer_fetch_next
    return self.buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 536, in buffer_fetch_next
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 536, in <genexpr>
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 787, in buffer_fetch
    return self.output.buffer_fetch(start, end)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 95, in buffer_fetch
    newsegment = self._buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 117, in _buffer_fetch_next
    return self.buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 236, in buffer_fetch_next
    input = self.source.buffer_fetch(start, end)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 95, in buffer_fetch
    newsegment = self._buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 117, in _buffer_fetch_next
    return self.buffer_fetch_next(samples)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 433, in buffer_fetch_next
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/filtering/filterbank.py", line 433, in <genexpr>
    inputs = tuple(s.buffer_fetch(start, end) for s in self.source)
  File "/Users/jiayueliu/cvs/anaconda/anaconda2/envs/brian/lib/python3.6/site-packages/brian2hears/bufferable.py", line 79, in buffer_fetch
    raise IndexError('Attempted to fetch output that has disappeared from the buffer.')
IndexError: Attempted to fetch output that has disappeared from the buffer.

**Comment by thesamovar** [comment]
Can you post your question to our email support list https://groups.google.com/forum/#!forum/briansupport including a minimal sample of code that reproduces the problem?

**Comment by jiayueLiiu** [comment]
Posted, thanks!
